version: "3.9" 

volumes:
  mongodb_volume:

services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Moscow
      - DATASOURCE_HOST=mongodb
      - DATASOURCE_PORT=27017
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8080

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db